apiVersion: v1
kind: Pod
metadata:
  name: admin-frontend
  namespace: shop
  labels:
    app.kubernetes.io/name: admin-frontend
spec:
  containers:
    - name: frontend
      image: uphiller/shop:admin-frontend
      ports:
        - containerPort: 80
      imagePullPolicy: Always

  imagePullSecrets:
    - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: admin-frontend-svc
  namespace: shop
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: admin-frontend
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-admin-frontend
  namespace: shop
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: "nginx"
  rules:
    - host: "admin-frontend.bettercodelab.com"
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: admin-frontend-svc
                port:
                  number: 80