apiVersion: v1
kind: Pod
metadata:
  name: backend
  namespace: shop
  labels:
    app.kubernetes.io/name: backend
spec:
  containers:
    - name: backend
      image: uphiller/shop:system
      ports:
        - containerPort: 8080
  imagePullSecrets:
    - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: shop
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: backend
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-backend
  namespace: shop
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: "nginx"
  rules:
    - host: "backend.bettercodelab.com"
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: backend-svc
                port:
                  number: 8080